// gen-qr.mjs — OFFLINE QR precompute (devDependency 'qrcode'; task 011).
// The game ships NO runtime QR dependency and NO binary assets: this script
// runs once at authoring time, bakes the Ko-fi URL into a plain module matrix,
// and writes src/data/kofi-qr.js as a compact constant the pack draws by hand
// on its canvas textures. Re-run this whenever KOFI_URL changes:
//   node tools/gen-qr.mjs
// Error-correction level Q (25% recovery) buys tolerance for the toon/curve
// rendering + camera keystone while keeping the module count low (version 3,
// 29×29) so each module lands on plenty of screen pixels for jsQR to decode.
import QRCode from 'qrcode';
import { writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const KOFI_URL = 'https://ko-fi.com/jimbobuildsope';
const ECL = 'Q';

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, '..', 'src', 'data', 'kofi-qr.js');

const qr = QRCode.create(KOFI_URL, { errorCorrectionLevel: ECL });
const size = qr.modules.size;
const data = qr.modules.data;                 // row-major Uint8Array, 1 = dark
const rows = [];
for (let y = 0; y < size; y++) {
  let s = '';
  for (let x = 0; x < size; x++) s += data[y * size + x] ? '1' : '0';
  rows.push(s);
}

const body = `// GENERATED by tools/gen-qr.mjs — DO NOT EDIT BY HAND.
// Precomputed QR module matrix for the Ko-fi support URL (task 011). Emitted
// as a compact constant so the game carries no runtime QR dependency and no
// binary asset; the kofi pack draws these modules onto its canvas textures
// with a quiet zone and dark-on-light contrast.
export const KOFI_URL = ${JSON.stringify(KOFI_URL)};
export const QR = {
  ecl: ${JSON.stringify(ECL)},
  version: ${qr.version},
  size: ${size},
  // one string per row, '1' = dark module, '0' = light
  rows: [
${rows.map(r => '    ' + JSON.stringify(r)).join(',\n')},
  ],
};
`;
writeFileSync(OUT, body);
console.log(`wrote ${OUT}`);
console.log(`  url=${KOFI_URL}  ecl=${ECL}  version=${qr.version}  size=${size}x${size}`);
